safe:        true
port: 4000

source:      .
destination: ./_site
plugins_dir:     ./_plugins

future:      true
lsi:         false
highlighter:    true
markdown:    kramdown
permalink:   pretty

kramdown:
  auto_ids: true
  input: GFM
