safe:        true
port: 4000

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
highlighter:    true
markdown:    kramdown
permalink:   pretty

kramdown:
  input: GFM
  auto_ids: false
